# Generated by Django 4.0.6 on 2022-09-01 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peofile',
            new_name='Profile',
        ),
    ]
