# Generated by Django 4.0.6 on 2022-09-01 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_pup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pup_date',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 15, 26, 47, 386339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('a', 'python'), ('b', 'django')], max_length=90, unique_for_date='pub_date'),
        ),
    ]
