# Generated by Django 4.0.6 on 2022-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_cateqory_remove_article_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cateqory',
            field=models.ManyToManyField(blank=True, to='blog.cateqory'),
        ),
    ]
