# Generated by Django 4.0.6 on 2022-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
