# Generated by Django 4.0.6 on 2022-10-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_new_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
