# Generated by Django 4.1.2 on 2022-10-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_article_options_cateqory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cateqory',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.cateqory'),
        ),
    ]
