# Generated by Django 4.1.3 on 2022-12-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_massege_created_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massege',
            new_name='Messege',
        ),
    ]
