# Generated by Django 4.1.3 on 2022-12-08 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_messege_age_messege_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 14, 1, 52, 121610, tzinfo=datetime.timezone.utc)),
        ),
    ]
