# Generated by Django 4.1.3 on 2023-01-01 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_messege_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='navid',
        ),
        migrations.AlterField(
            model_name='messege',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 17, 29, 56, 652639, tzinfo=datetime.timezone.utc)),
        ),
    ]
